apiVersion: v1
kind: ConfigMap
metadata:
  name: init-config
data:
  init_config.sh: |
    #!/bin/sh
  
    mkdir -p /jupyterhub/config
  
    cat > /jupyterhub/config/jupyterhub_config.py <<EOL
    c.JupyterHub.ip = '0.0.0.0'
    c.JupyterHub.port = 8000
    c.JupyterHub.hub_connect_ip = '127.0.0.1'
    c.JupyterHub.db_url = 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-service:5432/${POSTGRES_DB}'
    EOL